# Configuration for bakatsuki crawler

# MediaWiki API endpoint
api: https://www.baka-tsuki.org/project/api.php

# Root page used to discover volume links
root_page: Owari_no_Chronicle  # used if namespace_name is not set

# Directory (relative) to store raw .wiki exports
# will use cwd if not set
output_dir: 0_wiki_exports
  
# Only crawl pages whose title starts with this prefix (leave unset for legacy Horizon:Volume discovery)
prefix_filter: "Owari"
