# Configuration for EPUB to MD converter
epub:
  combine_to_one_md: false  # true to merge all chapters into one MD file
  input_dir: ./input        # optional, default cwd
  output_dir: ./output      # default output dir

image_hosting:
  method: imgbox            # currently only imgbox supported
  email: ""                 # imgbox account email
  password: ""              # imgbox account password
  album_id: ""              # optional album id for uploaded images
