# config.yml (must be next to main.py)

# freeimage.host api key
api_key: "6d207e02198a847aa98d0a2a901485a5" 

# directory to look for .epub files, relative to CWD (CWD is root)
input_dir: "0_epub"         

# directory to save output .md files, relative to CWD
output_dir: "1_input_md" 

# images upload settings
# images per upload batch
batch_size: 5          
# seconds between batches (recommended at least 1 second to avoid rate limiting)
sleep_between_batches: 1  
