active_task:
  task_name: "Dịch văn bản"
  input_dir: "file_input/volume_1"

translate_api:
  provider: gemini
  model: gemini-2.5-pro
  temperature: 1.3
  concurrent_requests: 10
  max_tokens: 15000
  thinking_budget: 2000
  delay: 45
  max_retries: 5  # Số lần retry tự động cho các segment lỗi

paths:
  output_trans: "file_output"
  log_trans: "inventory/logs/translator"
  context_dir: "inventory/context"
  prompt_file: "inventory/prompt/prompt.txt"
  title_prompt_file: "inventory/prompt/title_prompt.txt"
  context_prompt_file: "inventory/prompt/context_prompt.txt"

title_api:
  provider: gemini
  model: gemini-2.5-flash
  temperature: 1.3
  concurrent_requests: 20
  max_tokens: 100
  thinking_budget: 0
  delay: 0

title_translation:
  enabled: true


cleaner:
  enabled: true
  remove_thinking_blocks: true
